(** Effectful features for Mehari server. *)

open Mehari

type path = string

(** {1 Static files serving} *)

val respond_document : ?mime:Mime.t -> path -> Response.t
(** Same as {!val:Mehari.Response.respond} but respond with content of given
    [filename] and use given {!type:Mehari.Mime.t} as mime type. If [filename]
    is not present on filesystem or an error occured, responds with
    {!val:Mehari.Status.not_found}. If [mime] parameter is not supplied,
    document is served as {!val:Mehari.Mime.app_octet_stream}. *)

val static :
  ?handler:(path -> handler) ->
  ?dir_listing:
    (([ `Regular_file | `Directory | `Other ] * string) list -> handler) ->
  ?index:path ->
  ?show_hidden:bool ->
  path ->
  string ->
  handler
(** [static dir target] validates [target] by checking that it is relative and
    does not contain parent directory references. If these checks fail, responds
    with {!val:Mehari.Status.not_found}.

    If the checks succeed, [static] calls [handler path request], where [path]
    is the path generated by the concatenation of directory [dir] and path of
    request. [handler] defaults to {!val:respond_document}.

    If a directory is requested, [static] will look for a file named [index] in
    that directory to return. Otherwise, a directory file listing will be
    generated by calling [dir_listing [ filename; ... ] request]. [index] is
    default on [index.gmi].

    Mime type of the served ressource is guessed by checking file name. Note
    that file names of the form [*.gmi] will be served as [text/gemini].

    [show_hidden] decides whether hidden files should be listed. It defaults to
    [false] for security reasons. *)

(** {1 CGI}

    Mehari supports CGI scripting as described in RFC 3875

    The CGI script must write its gemini response on its stdout. Status code and
    meta string are on the first line, and the optional response body on
    subsequent lines. The bytes generated by the CGI script will be forwarded
    verbatim to the Gemini client, without any additional modification by the
    server.

    Some variables ([CONTENT_LENGTH], [CONTENT_TYPE], [REMOTE_IDENT],
    [REMOTE_METHOD], [REMOTE_USER], [REQUEST_METHOD]) volontary have an empty
    string value to be compatibile as much as possible with non-gemini CGI
    script.

    @see < https://www.rfc-editor.org/rfc/rfc3875 >
      For the full CGI specification.

    {2 Examples}

    Let's assume that client requested the following URL:
    [gemini://localhost/cgi/script.cgi?an_input] and the response generation is
    handled by a CGI script located at [/var/cgi-bin/script.cgi] on server. CGI
    variables values are:

    - [AUTH_TYPE] is ["Certificate"] if a client certificate is provided, empty
      otherwise.
    - [CONTENT_LENGTH] is empty
    - [CONTENT_TYPE] is empty
    - [GATEWAY_INTERFACE] is [CGI/1.1]
    - [PATH_INFO] is [/cgi/script.cgi]
    - [PATH_TRANSLATED] is [/cgi/script.cgi]
    - [QUERY_STRING] is [an_input]
    - [REMOTE_ADDR] is [127.0.0.1:client_port]
    - [REMOTE_HOST] is same as [127.0.0.1]
    - [REMOTE_IDENT] is empty
    - [REMOTE_METHOD] is empty
    - [REMOTE_USER] is empty
    - [REQUEST_METHOD] is empty
    - [SCRIPT_NAME] is [/var/cgi-bin/script.cgi]
    - [SERVER_NAME] is [localhost]
    - [SERVER_PORT] is [1965]
    - [SERVER_PROTOCOL] is [GEMINI]
    - [SERVER_SOFTWARE] is [Mehari/1.0]
    - [TLS_CLIENT_HASH] is the SHA-256 sum of the client certificate if it is
      provided, empty otherwise
    - [TLS_CLIENT_SUBJECT] is the client certificate Subject common name if it
      is provided, empty otherwise
    - [TLS_CLIENT_ISSUER] is the client certificate Issuer common name if it is
      provided, empty otherwise *)

val run_cgi :
  ?timeout:float -> ?non_parsed:bool -> string -> Request.t -> Response.t
(** [run_cgi ?timeout ?non_parsed script_path req] executes the CGI script
    located at [script_path] and return a response containing script's stdout
    output. Responds with {!val:Mehari.Status.cgi_error} in case of error or
    [timeout] exceeding.

    - [timeout] is expressed in seconds and defaults to [5.0].
    - [non_parsed] decides if NPH (Non-Parsed Header CGI feature) is enable. It
      allow to passes all responsibility for response processing to script which
      means that server no longer checks correctness of the script output. Use
      it with caution. Defaults to [false]. *)

(** {1 Server} *)

val run :
  ?timeout:float ->
  ?port:int ->
  ?reuseport:bool ->
  ?reuseaddr:bool ->
  ?backlog:int ->
  certs:Tls.Config.certchain list ->
  Ipaddr.Prefix.t ->
  handler ->
  unit
(** [run ?timeout ?port ?reuseport ?reuseaddr ?backlog ~certs ip handler] runs a
    Gemini server.

    - [ip] is the server IP addresses.
    - [certs] is the TLS certchains used. See section "Certificate selection" in
      {!Mehari.Server} module.
    - [port] is the port to listen on. Defaults to [1965].
    - [timeout] is the maximum time in seconds to wait for client to write a
      request after the TLS handshake. Defaults to 5 seconds.
    - [backlog] is the the number of pending connections that can be queued.
      Defaults to [64].
    - [reuseaddr] allows reuse of local addresses for bind. Defaults to true.
    - [reuseport] allows reuse of address and port bindings. Defaults to true.
*)
