(executable
 (name unikernel)
 (link_flags :standard -cclib "-z solo5-abi=hvt")
 (foreign_stubs
  (language c)
  (names manifest))
 (libraries
  mehari
  mehari-mirage
  cmdliner
  logs.cli
  logs.fmt
  fmt.cli
  mkernel
  mirage-crypto-rng-mkernel
  mnet
  mnet-cli
  mnet-tls
  tls
  mfat
  mirage-ptime.solo5
  gmp))

(rule
 (targets manifest.c)
 (enabled_if
  (= %{context_name} "default"))
 (action
  (write-file manifest.c "")))

(rule
 (targets manifest.c)
 (deps manifest.json)
 (enabled_if
  (= %{context_name} "solo5"))
 (action
  (run solo5-elftool gen-manifest manifest.json manifest.c)))
