(** An IO module Mehari implementation for Unix and Windows using Lwt. Contains
    also extra features based on Unix filesystem such as {!section-cgi}. *)

open Mehari

(** {1 Net} *)

include Mehari_mirage.S
(** @closed *)

(** @closed *)
include FS with module IO := IO and type dir_path := string

(** {1:cgi CGI} *)

(** Mehari supports CGI scripting as described in RFC 3875

    The CGI script must write its gemini response on its stdout. Status code and
    meta string are on the first line, and the optional response body on
    subsequent lines. The bytes generated by the CGI script will be forwarded
    verbatim to the Gemini client, without any additional modification by the
    server.

    Some variables ([CONTENT_LENGTH], [CONTENT_TYPE], [REMOTE_IDENT],
    [REMOTE_METHOD], [REMOTE_USER], [REQUEST_METHOD]) volontary have an empty
    string value to be compatibile as much as possible with non-gemini CGI
    script.

    @see < https://www.rfc-editor.org/rfc/rfc3875 > For the CGI specification.

    {2 Examples}

    Let's assume that client requested the following URL:
    [gemini://localhost/cgi/script.cgi?an_input] and the response generation is
    handled by a CGI script located at [/var/cgi-bin/script.cgi] on server. CGI
    variables values are:

    - [AUTH_TYPE] is ["Certificate"] if a client certificate is provided, empty
      otherwise.
    - [CONTENT_LENGTH] is empty
    - [CONTENT_TYPE] is empty
    - [GATEWAY_INTERFACE] is [CGI/1.1]
    - [PATH_INFO] is [/cgi/script.cgi]
    - [PATH_TRANSLATED] is [/cgi/script.cgi]
    - [QUERY_STRING] is [an_input]
    - [REMOTE_ADDR] is [127.0.0.1]
    - [REMOTE_HOST] is same as [REMOTE_ADDR]
    - [REMOTE_IDENT] is empty
    - [REMOTE_METHOD] is empty
    - [REMOTE_USER] is empty
    - [REQUEST_METHOD] is empty
    - [SCRIPT_NAME] is [/var/cgi-bin/script.cgi]
    - [SERVER_NAME] is [localhost]
    - [SERVER_PORT] is [1965]
    - [SERVER_PROTOCOL] is [GEMINI]
    - [SERVER_SOFTWARE] is [Mehari/1.0]
    - [TLS_CLIENT_HASH] is the SHA-256 sum of the client certificate if it is
      provided, empty otherwise
    - [TLS_CLIENT_SUBJECT] is the client certificate Subject common name if it
      is provided, empty otherwise
    - [TLS_CLIENT_ISSUER] is the client certificate Issuer common name if it is
      provided, empty otherwise *)

val run_cgi : ?timeout:float -> ?non_parsed:bool -> string -> handler
(** [run_cgi ?timeout ?non_parsed script_path req] executes the CGI script
    located at [script_path] and return a {!type:Mehari.response} containing
    script's stdout. Responds with {!val:Mehari.Status.cgi_error} in case of
    error or [timeout] exceeding.

    - [timeout] is expressed in seconds and defaults to [5.0].
    - [non_parsed] decides if NPH (Non-Parsed Header CGI feature) is enable. It
      allow to passes all responsibility for response processing to script which
      means that server no longer checks correctness of script output. Use it
      with caution. Defaults to [false]. *)

(** {1 Entry point} *)

val run_lwt :
  ?port:int ->
  ?verify_url_host:bool ->
  ?timeout:float ->
  ?v4:Ipaddr.V4.Prefix.t ->
  ?v6:Ipaddr.V6.Prefix.t ->
  certs:Certs.t ->
  handler ->
  unit Lwt.t
(** See {!val:Mehari_mirage.S.run}. *)

val run :
  ?port:int ->
  ?verify_url_host:bool ->
  ?timeout:float ->
  ?v4:Ipaddr.V4.Prefix.t ->
  ?v6:Ipaddr.V6.Prefix.t ->
  certs:Certs.t ->
  handler ->
  unit
(** Like {!val:run_lwt} but calls [Lwt_main.run] internally. *)
