(** An IO module Mehari implementation for Unix and Windows using Lwt. Contains
    also extra features based on Unix filesystem such as {!section-cgi}. *)

(** {1 Net} *)

include Mehari_mirage.S
(** @closed *)

(** @closed *)
include Mehari.FS with module IO := IO and type dir_path := string

(** {1:cgi CGI} *)

(** Mehari supports CGI scripting as described in RFC 3875

    The CGI script must write its gemini response on its stdout. Status code and
    meta string are on the first line, and the optional response body on
    subsequent lines. The bytes generated by the CGI script will be forwarded
    verbatim to the Gemini client, without any additional modification by the
    server.

    {2 Environment variables}

    Mehari sets the following environment variables in CGI scripts: [AUTH_TYPE],
    [CONTENT_LENGTH], [CONTENT_TYPE], [GATEWAY_INTERFACE], [PATH_INFO],
    [PATH_TRANSLATED], [QUERY_STRING], [REMOTE_ADDR], [REMOTE_HOST],
    [REMOTE_IDENT], [REMOTE_METHOD], [REMOTE_USER], [SCRIPT_NAME],
    [SERVER_NAME], [SERVER_PORT], [SERVER_PROTOCOL], [SERVER_SOFTWARE],
    [TLS_CLIENT_HASH], [TLS_CLIENT_SUBJECT] and [TLS_CLIENT_ISSUER].

    Some variables volontary have an empty string value to be compatibile as
    much as possible with non-gemini CGI script.

    @see < https://www.rfc-editor.org/rfc/rfc3875 > For the CGI specification.

    {3 Examples}

    Let's say that the url requested is
    [gemini://localhost/cgi/foo.cgi?an_input]:

    - [AUTH_TYPE]: ["Certificate"] if a client certificate is provided, empty
      otherwise.
    - [CONTENT_LENGTH]: empty
    - [CONTENT_TYPE]: empty
    - [GATEWAY_INTERFACE]: [CGI/1.1]
    - [PATH_INFO] (example value: [/cgi/foo.cgi])
    - [PATH_TRANSLATED] (example value: [/cgi/foo.cgi])
    - [QUERY_STRING] (example value: [an_input])
    - [REMOTE_ADDR] (example value: [127.0.0.1])
    - [REMOTE_HOST]: same as [REMOTE_ADDR]
    - [REMOTE_IDENT]: empty
    - [REMOTE_METHOD]: empty
    - [REMOTE_USER]: client certificate common if it is provided, empty
      otherwise
    - [SCRIPT_NAME] (example value: [/var/cgi/foo.cgi])
    - [SERVER_NAME] (example value: [/var/cgi/foo.cgi])
    - [SERVER_PORT] (example value: [1965])
    - [SERVER_PROTOCOL]: [GEMINI].
    - [SERVER_SOFTWARE] (example value: [Mehari/1.0])
    - [TLS_CLIENT_HASH]: SHA-256 sum of the client certificate if it is
      provided, empty otherwise
    - [TLS_CLIENT_SUBJECT]: client certificate Subject common name if it is
      provided, empty otherwise
    - [TLS_CLIENT_ISSUER]: client certificate Issuer common name if it is
      provided, empty otherwise *)

val run_cgi :
  ?timeout:float ->
  ?nph:bool ->
  string ->
  Mehari.request ->
  Mehari.response Lwt.t
(** [run_cgi ?timeout ?nph script_path req] executes the given file as a CGI
    script and return a {!type:Mehari.response} based on bytes printed on stdout
    by script. Responds with {!val:Mehari.cgi_error} in case of error or
    [timeout] exceeding.

    - [timeout] defaults to [5.0].
    - [nph] decides if NPH (Non-Parsed Header) is enable. Defaults to [false].
*)

(** {1 Entry point} *)

val run_lwt :
  ?port:int ->
  ?verify_url_host:bool ->
  ?config:Tls.Config.server ->
  ?timeout:float ->
  certchains:Tls.Config.certchain list ->
  ?v4:Ipaddr.V4.Prefix.t ->
  ?v6:Ipaddr.V6.Prefix.t ->
  handler ->
  unit Lwt.t
(** See {!val:Mehari_mirage.S.run}. *)

val run :
  ?port:int ->
  ?verify_url_host:bool ->
  ?config:Tls.Config.server ->
  ?timeout:float ->
  certchains:Tls.Config.certchain list ->
  ?v4:Ipaddr.V4.Prefix.t ->
  ?v6:Ipaddr.V6.Prefix.t ->
  handler ->
  unit
(** Like {!val:run_lwt} but calls [Lwt_main.run] internally. *)
